# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

# Executer le script quand push sur /main
on: push

jobs:
  deploy:
    name : Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name : Pull project to Ubuntu
        uses: actions/checkout@v3

      - name : Setup node on Ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name : Install project dependencies
        run: npm ci

      - name: Deploy to Droplet
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.HOST }}
          username : ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "*"
          target: /home/

